### ISSUE TITLE
Private Browsing

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#25]
As a user, I would like my search history to not be logged.

- [x]  [#87] Toggle switch in order to activate private browsing @sophiaquach16
- [x]  [#88] Prevent viewed articles from saving to search history @jadmalek @sophiaquach16 
- [x]  [#89] Adjust UI of application to be in incognito (dark) mode @jadmalek @sophiaquach16  
- [x] Unit/UI tests for tasks

[Story Points: 8]
[Priority: High]
[Risk: High]
