### ISSUE TITLE
Enhancement of Trip Planner

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#26]
Subtask of #21.

- [x] [#53] Finish fragment controller @artemmikhalitsin [2 points]
     --> Prompt user to save any changes when exiting planner via the back button (a 0 point task, #58, that will ultimately not be implemented for this feature)
- [x] [#54] Get the related articles @mnhn329 @amawai [4 points]
- [x] [#55] Implement save trip, delete trip, edit trip (potentially different views for each) @SunXP   [3 points]
- [x] [#57] Share trips @jadmalek [1 point]
- [#56, see explanation in acceptance testing comment for reasons behind lack of completion] Destination history @abhandal  [3 points]

[Story Point: 13]
[Priority: High]
[Risk: High]
