### ISSUE TITLE
Refactor travel package structure and naming 

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#41]
As a developer I would like to improve the current file structure of the travel package (implemented for #22) for better readability and consistency.

- [x] [#47]  Rename subpackages classes and pertinent methods within travel package@jadmalek
- [x] [#48] Naming consistency (ids for buttons and other visual components should be standardized) @jadmalek 
- [x] [#50] Refactor code to comply with coding conventions @amawai
- [x] [#51] Buttons should all look the same (i.e. same shape and color for similar functions) [@amawai
 
[Story Points: 2]
[Risk: Low]
[Priority: High]
