### ISSUE TITLE
Addition of Acceptance Tests for Release 2

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#60]
As a developer, I would like to construct acceptance tests for each of the code and feature based user stories in Release 2.

US #22 (trip planner set-up,  Sprint 3), #20 (sharing of reading list feature, Sprint 3) and #26 (trip planner feature enhancement, Sprint 4) will specifically be accounted for. These tests will be displayed in the issues for the users stories from Sprint 3 (by @jadmalek) and in the following task issues for the trip planner enhancement user story. 

- [x] Save, delete and edit a new trip [#55] @jadmalek
- [x] Select departure date [#22, addressed in Sprint 3 but indicated here as it is a key part of the trip planner feature flow] @jadmalek 
- [x] View destination history of a trip [#56] @sophiaquach16
- [x] Get the related articles for a trip's landmarks [#54] @sophiaquach16
- [x] Share a trip with an external service [#57] @jadmalek

[Story Points: 0]
[Risk: Low]
[Priority: Medium]
