### ISSUE TITLE
Finalization of Trip Planner

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#70]
Subtask of #21.

- [x] [#99] Layout fixes (improve the look of the trip planner screens so they look more like the mockups) [2 points] @artemmikhalitsin 
- [x] [#56] Destination history [3 points] @abhandal 
- [x] [#100] Update trip database table to store landmarks [1 point] @artemmikhalitsin 
- [x] [#101] Have landmarks selected by a user for a trip be indicated as such in the Landmarks page or be displayed in a separate page particular for this purpose [2 points] @jadmalek @sophiaquach16 
- [x] Additional Unit/UI Tests

[Story Points: 8] - 3 for @artemmikhalitsin, 3 for @abhandal, 1 for @jadmalek and 1 for @sophiaquach16 
[Risk: Medium] - for all non-test tasks, low risk for test task
[Priority: High] - for all tasks

**Comment by amawai** [comment]
_See tasks #100 and #101 for acceptance tests and demo steps of the encompassed functionality_

Closed by #107, #109, #110.
