### ISSUE TITLE
Translation of Articles

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#71]
As a user, I would like to be able to select sections in an article (or the article as a whole) and have them be translated into a language of my choosing. 

- [x] Means to select article sections to be translated [#84]
- [x] Select language for article translation [#86]
- [x] Translation of article implementation [#85]
- [x] Unit/UI Tests 

[Story Points: 8] 4 for @abhandal and 4 for @SunXP 
[Risk: Medium]
[Priority: High]

**Comment by sophiaquach16** [comment]
**Acceptance Testing**

These acceptance tests characterize the expected behaviour the task was meant to exhibit.

| Test #         | Inputs | Expected Output  | Status |
| ------------------ | ------------- | ------------- | ------------- |
| 1. Translation icon exists.  | Select the desired text to be translated.  | A translation icon (the shape of a pencil) on the top second to right button appears. | PASS  |
| 2. The text is displayed.  | Click on the translation icon.  | “To translate:” is followed by the desired text that was selected.  | PASS  |
| 3. Picking a target language.  | Press on the “Select language” dropdown menu. | A list of languages appear.   | PASS  |
| 4. The text is translated.  | Click on a language from the “Select language” dropdown menu. | “Translated:” is followed by the a translated version of the text that was selected.   | PASS  |

**Demo Steps**

1. Launch the application
2. Click on the “Search Wikipedia” bar
3. Enter a desired search
4.  Click on the article that corresponds most to the desired search
