### ISSUE TITLE
Article Search by Image

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#74]
As a user, I would like to be able to search for an article based on an image capture my camera. 

- [x] [#96] Addition camera icon + open camera on click  
- [x] [#97] Send picture taken by user through google api 
- [x] [#98] Interpret results from api and redirect to relevant articles (show user list of suggested/most relevant articles)  
- [x] Unit/UI Tests

[Story Points: 8 points] 2 for @SunXP, 3 for @mnhn329, 3 for @amawai
[Risk: High] - see task issues for specific risk assessment
[Priority: High] - same for all tasks

**Comment by amawai** [comment]
#96, #97, and #98 have been completed, fulfilling this feature.
Closed by #108

**Comment by sophiaquach16** [comment]
**Acceptance Testing**

These acceptance tests characterize the expected behaviour this user story's implementations are to exhibit. The level of accuracy and ability for image search (by camera or alternative image source) to retrieve results/labels based on the indicated images is limited by the API used for the implementation, Clarifai. Also, once an image search is conducted and results are failed to be returned, an error prompt appears and a loading bar for the image search at the top of the main application page will continue going (will not affect functionality of remainder of application).

| Test #         | Inputs | Expected Output  | Status |
| ----------------------- | ------------- | ------------- | ------------- |
| 1. Display of menu to conduct article search by image.  | Select on 'image' button in search bar on main page of the application. | "Image Search: Select Source" appears, along with a list of source options. | PASS  |
| 2. Use of camera for image search.  |  Click on “Camera” option from the menu in test 1.  | Camera usage is now available, along with 'checkmark', 'refresh' and 'X' icons. | PASS
| 3. The photo chosen by the user is being processed.  |  Take a picture of an object or person and select on 'checkmark' icon. | “Recognizing image…” message is displayed. | PASS  |
| 4. Relevant results corresponding to the photo chosen are displayed.  | None. | A list of text card results appear.   | PASS  |
| 5. Display of list of word results correspond to Wikipedia articles.  | Click on a word result from the list. | The Wikipedia article corresponding to that word is displayed to the screen.   | PASS  |
| 6. Image search by selection of a difference image source.  | Repeat input from test 1, select on an alternative image source ('Gallery', for example), select the desired image, and repeat inputs from tests 4 and 5. | Same expected output as test 5.  | PASS

**Demo Steps**

1. Launch the application.
2. Click on the 'image' button of the “Search Wikipedia” bar, the button of a photo right before the microphone button.
3. Click on “Camera” OR “Gallery” for the Image Search: Select Source. 
4. If “Camera is chosen”, take a photo and press the checkmark button to confirm. If “Gallery”, choose the photo to be used.
5. Click on a word result from the list for the article to open up.

Closed by PR #108.
