### ISSUE TITLE
Article Reading Tracker With Note Taking

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#76]
As a user, I would like to be directed by the application to where I was last reading upon re-opening an article and take notes on the article. 

- [x] [#83] Determine how to save state of article when user closes it (bring user back to previous state when article is reopened)
-  Visual indicator of progress on article (optional)
- [x] [#82] Option to add a note where the user left off (icon to represent that a note has been left)
- [x] [#81] Store notes in a database

[Story Points: 8 points] 2 for @amawai, 3 for @artemmikhalitsin, 3 for @mnhn329
[Risk: High]
[Priority: High]
