### ISSUE TITLE
Implementation of Client-Side Note Taking 

### ISSUE THREAD

**Issue by amawai** [amawai/android-wikipedia-390#82]
Subtask of User Story [#76]
This subtask involves the design (UI, UX) and implementation of a flow in which the user can saves notes anywhere on a specific article (e.g. near the header, near a paragraph, etc.).

- [x] Implement a way for the user to create a note which would prompt the pop-up textbox to appear
- [x] Create pop-up input textbox that allows for the user to write notes
- [x] Implement a way to save, edit, delete notes (call the appropriate database helper methods)
- [x] Unit / UI tests

[Story Points: 3]
[Priority: High]
[Risk: High]
