### ISSUE TITLE
Addition of Acceptance Tests for Release 3

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#92]
As a developer, I would like to construct acceptance tests for each of the code and feature based user stories in Release 3.

US #25 (private browsing), #71 (translation of articles), #76 (article reading tracker), #70 (trip planner finalization) and #74 (article search by image) will specifically be accounted for. These tests will be displayed in the issues for the users stories from Sprints 5 and 6.

- [x] Private Browsing (place in #25 and #91) @jadmalek
- [x] Article Translation (place in #71 and #94) @sophiaquach16 
- [x] Article Tracker/Note Taker (place in #76 and #93) @jadmalek 
- [x] Trip Planner Finalization (place in tasks #56, #100 and #101 as well as PRs #66 and #110) @jadmalek
- [x] Article Search by Image (place in #74 and #108) @sophiaquach16

If tasks are demo-able and involve finer tuned acceptance tests, tests will be placed in the applicable task issues. 

[Story Points: 0]
[Risk: Low] - for all tasks 
[Priority: Medium] - for all tasks
